# Susan Borne
# Alex Zimmerman

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def __init__(self):
        self.collegeBox = QtWidgets.QComboBox(Form)
        if (self.handleValueUpdated(self.collegeBox)):
            self.collegeBox.valueUpdated.connect(self.handleValueUpdated)
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(550, 510)
        self.addStudent = QtWidgets.QLabel(Form)
        self.addStudent.setGeometry(QtCore.QRect(180, 30, 121, 16))
        self.addStudent.setObjectName("addStudent")
        self.student = QtWidgets.QLabel(Form)
        self.student.setGeometry(QtCore.QRect(31, 72, 48, 16))
        self.student.setObjectName("student")
        self.studentFirstBox = QtWidgets.QLineEdit(Form)
        self.studentFirstBox.setGeometry(QtCore.QRect(170, 60, 131, 21))
        self.studentFirstBox.setObjectName("studentFirstBox")
        self.studentLasrBox = QtWidgets.QLineEdit(Form)
        self.studentLasrBox.setGeometry(QtCore.QRect(320, 60, 121, 21))
        self.studentLasrBox.setObjectName("studentLasrBox")
        self.studentEmailBox = QtWidgets.QLineEdit(Form)
        self.studentEmailBox.setGeometry(QtCore.QRect(174, 103, 131, 21))
        self.studentEmailBox.setObjectName("studentEmailBox")
        self.collegeBox.setGeometry(QtCore.QRect(171, 132, 271, 26))
        self.collegeBox.setObjectName("collegeBox")
        self.collegeBox.addItem("")
        self.collegeBox.addItem("")
        self.collegeBox.addItem("")
        self.collegeBox.addItem("")
        self.collegeBox.addItem("")
        self.collegeBox.addItem("")
        self.collegeBox.addItem("")
        self.collegeBox.addItem("")
        self.collegeBox.addItem("")
        self.collegeBox.addItem("")
        self.collegeBox.addItem("")
        self.collegeBox.addItem("")
        self.college = QtWidgets.QLabel(Form)
        self.college.setGeometry(QtCore.QRect(31, 134, 46, 16))
        self.college.setObjectName("college")
        self.mentorLast = QtWidgets.QLabel(Form)
        self.mentorLast.setGeometry(QtCore.QRect(326, 246, 26, 16))
        self.mentorLast.setObjectName("mentorLast")
        self.studentFirst = QtWidgets.QLabel(Form)
        self.studentFirst.setGeometry(QtCore.QRect(172, 80, 27, 16))
        self.studentFirst.setObjectName("studentFirst")
        self.mentor = QtWidgets.QLabel(Form)
        self.mentor.setGeometry(QtCore.QRect(31, 226, 44, 16))
        self.mentor.setObjectName("mentor")
        self.studentEmail = QtWidgets.QLabel(Form)
        self.studentEmail.setGeometry(QtCore.QRect(31, 103, 121, 16))
        self.studentEmail.setObjectName("studentEmail")
        self.majorDropdown = QtWidgets.QComboBox(Form)
        self.majorDropdown.setGeometry(QtCore.QRect(170, 160, 271, 26))
        self.majorDropdown.setObjectName("majorDropdown")
        self.majorDropdown.addItem("")
        self.minorDropdown = QtWidgets.QComboBox(Form)
        self.minorDropdown.setGeometry(QtCore.QRect(170, 190, 271, 26))
        self.minorDropdown.setObjectName("minorDropdown")
        self.minorDropdown.addItem("")
        self.majors = QtWidgets.QLabel(Form)
        self.majors.setGeometry(QtCore.QRect(31, 164, 51, 16))
        self.majors.setObjectName("majors")
        self.minors = QtWidgets.QLabel(Form)
        self.minors.setGeometry(QtCore.QRect(31, 195, 51, 16))
        self.minors.setObjectName("minors")
        self.mentorEmail = QtWidgets.QLabel(Form)
        self.mentorEmail.setGeometry(QtCore.QRect(30, 270, 80, 16))
        self.mentorEmail.setObjectName("mentorEmail")
        self.antiGradDate = QtWidgets.QLabel(Form)
        self.antiGradDate.setGeometry(QtCore.QRect(30, 301, 135, 16))
        self.antiGradDate.setObjectName("antiGradDate")
        self.gradDate = QtWidgets.QLabel(Form)
        self.gradDate.setGeometry(QtCore.QRect(30, 332, 99, 16))
        self.gradDate.setObjectName("gradDate")
        self.activity = QtWidgets.QLabel(Form)
        self.activity.setGeometry(QtCore.QRect(30, 362, 105, 16))
        self.activity.setObjectName("activity")
        self.durp = QtWidgets.QLabel(Form)
        self.durp.setGeometry(QtCore.QRect(30, 393, 77, 16))
        self.durp.setObjectName("durp")
        self.lsuEdu = QtWidgets.QLabel(Form)
        self.lsuEdu.setGeometry(QtCore.QRect(310, 110, 56, 16))
        self.lsuEdu.setObjectName("lsuEdu")
        self.mentorFirst = QtWidgets.QLabel(Form)
        self.mentorFirst.setGeometry(QtCore.QRect(172, 246, 27, 16))
        self.mentorFirst.setObjectName("mentorFirst")
        self.mentorFirstBox = QtWidgets.QLineEdit(Form)
        self.mentorFirstBox.setGeometry(QtCore.QRect(172, 226, 131, 20))
        self.mentorFirstBox.setObjectName("mentorFirstBox")
        self.mentorLastBox = QtWidgets.QLineEdit(Form)
        self.mentorLastBox.setGeometry(QtCore.QRect(325, 226, 121, 20))
        self.mentorLastBox.setObjectName("mentorLastBox")
        self.studentLast = QtWidgets.QLabel(Form)
        self.studentLast.setGeometry(QtCore.QRect(320, 80, 26, 16))
        self.studentLast.setObjectName("studentLast")
        self.mentorEmailBox = QtWidgets.QLineEdit(Form)
        self.mentorEmailBox.setGeometry(QtCore.QRect(172, 270, 131, 21))
        self.mentorEmailBox.setObjectName("mentorEmailBox")
        self.antiGradScroll = QtWidgets.QDateEdit(Form)
        self.antiGradScroll.setGeometry(QtCore.QRect(172, 300, 110, 24))
        self.antiGradScroll.setObjectName("antiGradScroll")
        self.gradScroll = QtWidgets.QDateEdit(Form)
        self.gradScroll.setGeometry(QtCore.QRect(172, 330, 110, 24))
        self.gradScroll.setObjectName("gradScroll")
        self.activityBox = QtWidgets.QLineEdit(Form)
        self.activityBox.setGeometry(QtCore.QRect(172, 362, 131, 21))
        self.activityBox.setObjectName("activityBox")
        self.durpDropdown = QtWidgets.QComboBox(Form)
        self.durpDropdown.setGeometry(QtCore.QRect(172, 391, 141, 26))
        self.durpDropdown.setObjectName("durpDropdown")
        self.durpDropdown.addItem("")
        self.durpDropdown.addItem("")
        self.durpDropdown.addItem("")
        self.durpDropdown.addItem("")
        self.entryBox = QtWidgets.QDateTimeEdit(Form)
        self.entryBox.setGeometry(QtCore.QRect(172, 430, 194, 24))
        self.entryBox.setObjectName("entryBox")
        self.entryLabel = QtWidgets.QLabel(Form)
        self.entryLabel.setGeometry(QtCore.QRect(30, 430, 121, 16))
        self.entryLabel.setObjectName("entryLabel")
        self.Add = QtWidgets.QDialogButtonBox(Form)
        self.Add.setGeometry(QtCore.QRect(290, 460, 164, 32))
        self.Add.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.Add.setObjectName("Add")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addStudent.setText(_translate("Form", "Student Information"))
        self.student.setText(_translate("Form", "Student"))
        self.mentorLast.setText(_translate("Form", "Last"))
        self.studentFirst.setText(_translate("Form", "First"))
        self.mentor.setText(_translate("Form", "Mentor"))
        self.studentEmail.setText(_translate("Form", "Username (Email)"))
        self.majors.setText(_translate("Form", "Major"))
        self.minors.setText(_translate("Form", "Minor"))
        self.mentorEmail.setText(_translate("Form", "Mentor Email"))
        self.antiGradDate.setText(_translate("Form", "Anticipated Grad Date"))
        self.gradDate.setText(_translate("Form", "Graduation Date"))
        self.activity.setText(_translate("Form", "Activity Attended"))
        self.durp.setText(_translate("Form", "DURP status"))
        self.lsuEdu.setText(_translate("Form", "@lsu.edu"))
        self.mentorFirst.setText(_translate("Form", "First"))
        self.studentLast.setText(_translate("Form", "Last"))
        self.durpDropdown.setItemText(0, _translate("Form", "select one:"))
        self.durpDropdown.setItemText(1, _translate("Form", "Candidate"))
        self.durpDropdown.setItemText(2, _translate("Form", "Awardee"))
        self.durpDropdown.setItemText(3, _translate("Form", "Not enrolled"))
        self.collegeBox.setItemText(0, _translate("Form", "Select One:"))
        self.collegeBox.setItemText(1, _translate("Form", "College of Agriculture"))
        self.collegeBox.setItemText(2, _translate("Form", "College of Art and Design"))
        self.collegeBox.setItemText(3, _translate("Form", "E.J. Ourso College of Business"))
        self.collegeBox.setItemText(4, _translate("Form", "College of the Coast & Environment"))
        self.collegeBox.setItemText(5, _translate("Form", "College of Engineering"))
        self.collegeBox.setItemText(6, _translate("Form", "College of Human Sciences & Education"))
        self.collegeBox.setItemText(7, _translate("Form", "College of Humanities & Social Sciences"))
        self.collegeBox.setItemText(8, _translate("Form", "Manship School of Mass Communication"))
        self.collegeBox.setItemText(9, _translate("Form", "College of Music & Dramatic Arts"))
        self.collegeBox.setItemText(10, _translate("Form", "College of Science"))
        self.collegeBox.setItemText(11, _translate("Form", "University College Center for Freshman Year"))
        self.college.setText(_translate("Form", "College"))
        self.entryLabel.setText(_translate("Form", "Entry Completed on"))
        self.majorDropdown.setItemText(0, _translate("Form", "Select One:"))
        self.minorDropdown.setItemText(0, _translate("Form", "Select One (if applicable):"))

    def handleValueUpdated(self, value):
        if (self.collegeBox.currentIndex() == 1):
            self.majorDropdown.setItemText(0, translate("Agricultural Business, BS"))
            self.majorDropdown.addItem("Agricultural & Extension Education, BS")
            self.majorDropdown.addItem("Animal Sciences, BS")
            self.majorDropdown.addItem("Environ Management Systems, BS")
            self.majorDropdown.addItem("Nutrition & Food Sciences, BS")
            self.majorDropdown.addItem("Natural Resource Ecl & Mgt, BS")
            self.majorDropdown.addItem("Plant & Soil Systems, BS")
            self.majorDropdown.addItem("Textiles/Apparel/Merchand, BS")

        if (self.collegeBox.currentIndex() == 2):
            self.majorDropdown.addItem("Interior Design")
            self.majorDropdown.addItem("Landscape Architecture")
            self.majorDropdown.addItem("Studio Art")

        if (self.collegeBox.currentIndex() == 3):
            self.majorDropdown.addItem("Accounting")
            self.majorDropdown.addItem("Economics")
            self.majorDropdown.addItem("Entrepreneurship")
            self.majorDropdown.addItem("Finance")
            self.majorDropdown.addItem("General Business")
            self.majorDropdown.addItem("Info Systs and Decision Sci")
            self.majorDropdown.addItem("International Trade & Finance")
            self.majorDropdown.addItem("Management")
            self.majorDropdown.addItem("Marketing")

        if (self.collegeBox.currentIndex() == 4):
            self.majorDropdown.addItem("Coastal Environmental Science")
            self.majorDropdown.addItem("Applied Coastal Env Science")
            self.majorDropdown.addItem("Coastal Metereorology")
            self.majorDropdown.addItem("Environmental Health")
            self.majorDropdown.addItem("Environmental Law")
            self.majorDropdown.addItem("Environmental Sci & Research")

        if (self.collegeBox.currentIndex() == 5):
            self.majorDropdown.addItem("Biological Engineering")
            self.majorDropdown.addItem("Construction Management")
            self.majorDropdown.addItem("Civil Engineering")
            self.majorDropdown.addItem("Chemical Engineering")
            self.majorDropdown.addItem("Computer Science")
            self.majorDropdown.addItem("Electrical Engineering")
            self.majorDropdown.addItem("Computer Engineering")
            self.majorDropdown.addItem("Environmental Engineering")
            self.majorDropdown.addItem("Industrial Engineering")
            self.majorDropdown.addItem("Mechanical Engineering")
            self.majorDropdown.addItem("Petroleum Engineering")

        if (self.collegeBox.currentIndex() == 6):
            self.majorDropdown.addItem("Child and Family Studies")
            self.majorDropdown.addItem("Dual Cert Gen/Spec Edu 1-5")
            self.majorDropdown.addItem("Elem Grades Education")
            self.majorDropdown.addItem("Kinesiology")
            self.majorDropdown.addItem("Leadership and Human Resource Development")
            self.majorDropdown.addItem("PK-3 Teacher Certification")
            self.majorDropdown.addItem("Sport Administration")
            self.majorDropdown.addItem("Social Work")

        if (self.collegeBox.currentIndex() == 7):
            self.majorDropdown.addItem("Anthropology")
            self.majorDropdown.addItem("Communication Studies")
            self.majorDropdown.addItem("Communication Disorders")
            self.majorDropdown.addItem("Economics")
            self.majorDropdown.addItem("English")
            self.majorDropdown.addItem("French")
            self.majorDropdown.addItem("Geography")
            self.majorDropdown.addItem("History")
            self.majorDropdown.addItem("International Studies")
            self.majorDropdown.addItem("Interdisciplinary Studies")
            self.majorDropdown.addItem("Liberal Arts")
            self.majorDropdown.addItem("Philosophy")
            self.majorDropdown.addItem("Political Science")
            self.majorDropdown.addItem("Psychology")
            self.majorDropdown.addItem("Screen Arts")
            self.majorDropdown.addItem("Sociology")
            self.majorDropdown.addItem("Spanish")

        if (self.collegeBox.currentIndex() == 8):
            self.majorDropdown.addItem("Mass Communication")

        if (self.collegeBox.currentIndex() == 9):
            self.majorDropdown.addItem("Music, BS")
            self.majorDropdown.addItem("Music Education")
            self.majorDropdown.addItem("Music, BM")
            self.majorDropdown.addItem("Theatre")

        if (self.collegeBox.currentIndex() == 10):
            self.majorDropdown.addItem("Biochemistry")
            self.majorDropdown.addItem("Biological Sciences")
            self.majorDropdown.addItem("Chemistry")
            self.majorDropdown.addItem("Geology-Professional")
            self.majorDropdown.addItem("Mathematics")
            self.majorDropdown.addItem("Microbiology")
            self.majorDropdown.addItem("Physics")

        if (self.collegeBox.currentIndex() == 11):
            self.majorDropdown.addItem("Undecided - Arts & Humanities")
            self.majorDropdown.addItem("Undecided - Sci & Engineering")
            self.majorDropdown.addItem("Undecided - Social Sciences")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

