#Susan Borne
#Alex Zimmerman

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(819, 749)
        font = QtGui.QFont()
        font.setKerning(False)
        Form.setFont(font)
        self.addStudent = QtWidgets.QLabel(Form)
        self.addStudent.setGeometry(QtCore.QRect(180, 30, 121, 16))
        self.addStudent.setObjectName("addStudent")
        self.student = QtWidgets.QLabel(Form)
        self.student.setGeometry(QtCore.QRect(31, 72, 48, 16))
        self.student.setObjectName("student")
        self.studentFirstBox = QtWidgets.QLineEdit(Form)
        self.studentFirstBox.setGeometry(QtCore.QRect(170, 60, 131, 21))
        self.studentFirstBox.setObjectName("studentFirstBox")
        self.studentLastBox = QtWidgets.QLineEdit(Form)
        self.studentLastBox.setGeometry(QtCore.QRect(320, 60, 121, 21))
        self.studentLastBox.setObjectName("studentLastBox")
        self.studentEmailBox = QtWidgets.QLineEdit(Form)
        self.studentEmailBox.setGeometry(QtCore.QRect(174, 103, 131, 21))
        self.studentEmailBox.setObjectName("studentEmailBox")
        self.mentorLast = QtWidgets.QLabel(Form)
        self.mentorLast.setGeometry(QtCore.QRect(330, 300, 26, 16))
        self.mentorLast.setObjectName("mentorLast")
        self.studentFirst = QtWidgets.QLabel(Form)
        self.studentFirst.setGeometry(QtCore.QRect(170, 80, 27, 16))
        self.studentFirst.setObjectName("studentFirst")
        self.mentor = QtWidgets.QLabel(Form)
        self.mentor.setGeometry(QtCore.QRect(31, 286, 71, 16))
        self.mentor.setObjectName("mentor")
        self.studentEmail = QtWidgets.QLabel(Form)
        self.studentEmail.setGeometry(QtCore.QRect(31, 103, 121, 16))
        self.studentEmail.setObjectName("studentEmail")
        self.majors = QtWidgets.QLabel(Form)
        self.majors.setGeometry(QtCore.QRect(31, 174, 51, 16))
        self.majors.setObjectName("majors")
        self.minors = QtWidgets.QLabel(Form)
        self.minors.setGeometry(QtCore.QRect(31, 255, 61, 16))
        self.minors.setObjectName("minors")
        self.mentorEmail = QtWidgets.QLabel(Form)
        self.mentorEmail.setGeometry(QtCore.QRect(480, 280, 101, 16))
        self.mentorEmail.setObjectName("mentorEmail")
        self.antiGradDate = QtWidgets.QLabel(Form)
        self.antiGradDate.setGeometry(QtCore.QRect(30, 491, 135, 16))
        self.antiGradDate.setObjectName("antiGradDate")
        self.gradDate = QtWidgets.QLabel(Form)
        self.gradDate.setGeometry(QtCore.QRect(30, 522, 99, 16))
        self.gradDate.setObjectName("gradDate")
        self.durp = QtWidgets.QLabel(Form)
        self.durp.setGeometry(QtCore.QRect(30, 462, 77, 16))
        self.durp.setObjectName("durp")
        self.lsuEdu = QtWidgets.QLabel(Form)
        self.lsuEdu.setGeometry(QtCore.QRect(310, 110, 56, 16))
        self.lsuEdu.setObjectName("lsuEdu")
        self.mentorFirst = QtWidgets.QLabel(Form)
        self.mentorFirst.setGeometry(QtCore.QRect(180, 300, 27, 16))
        self.mentorFirst.setObjectName("mentorFirst")
        self.mentorFirstBox = QtWidgets.QLineEdit(Form)
        self.mentorFirstBox.setGeometry(QtCore.QRect(174, 279, 131, 21))
        self.mentorFirstBox.setObjectName("mentorFirstBox")
        self.mentorLastBox = QtWidgets.QLineEdit(Form)
        self.mentorLastBox.setGeometry(QtCore.QRect(326, 279, 131, 21))
        self.mentorLastBox.setObjectName("mentorLastBox")
        self.studentLast = QtWidgets.QLabel(Form)
        self.studentLast.setGeometry(QtCore.QRect(320, 80, 26, 16))
        self.studentLast.setObjectName("studentLast")
        self.mentorEmailBox = QtWidgets.QLineEdit(Form)
        self.mentorEmailBox.setGeometry(QtCore.QRect(580, 280, 191, 21))
        self.mentorEmailBox.setObjectName("mentorEmailBox")
        self.durpDropdown = QtWidgets.QComboBox(Form)
        self.durpDropdown.setGeometry(QtCore.QRect(170, 460, 141, 26))
        self.durpDropdown.setObjectName("durpDropdown")
        self.durpDropdown.addItem("")
        self.durpDropdown.addItem("")
        self.durpDropdown.addItem("")
        self.durpDropdown.addItem("")
        self.Add = QtWidgets.QDialogButtonBox(Form)
        self.Add.setGeometry(QtCore.QRect(290, 580, 164, 32))
        self.Add.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.Add.setObjectName("Add")
        self.collegeBox = QtWidgets.QComboBox(Form)
        self.collegeBox.setEnabled(True)
        self.collegeBox.setGeometry(QtCore.QRect(170, 140, 311, 26))
        self.collegeBox.setObjectName("collegeBox")
        self.collegeBox.addItem("")
        self.collegeBox.addItem("")
        self.collegeBox.addItem("")
        self.collegeBox.addItem("")
        self.collegeBox.addItem("")
        self.collegeBox.addItem("")
        self.collegeBox.addItem("")
        self.collegeBox.addItem("")
        self.collegeBox.addItem("")
        self.collegeBox.addItem("")
        self.collegeBox.addItem("")
        self.collegeBox.addItem("")
        self.collegeBox.addItem("")
        self.college = QtWidgets.QLabel(Form)
        self.college.setGeometry(QtCore.QRect(31, 144, 101, 16))
        self.college.setObjectName("college")
        self.entryBox = QtWidgets.QDateTimeEdit(Form)
        self.entryBox.setGeometry(QtCore.QRect(170, 550, 194, 24))
        self.entryBox.setObjectName("entryBox")
        self.entryLabel = QtWidgets.QLabel(Form)
        self.entryLabel.setGeometry(QtCore.QRect(30, 550, 121, 16))
        self.entryLabel.setObjectName("entryLabel")
        self.majorDropdown = QtWidgets.QComboBox(Form)
        self.majorDropdown.setGeometry(QtCore.QRect(170, 170, 311, 26))
        self.majorDropdown.setObjectName("majorDropdown")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.majorDropdown.addItem("")
        self.collegeBox_2 = QtWidgets.QComboBox(Form)
        self.collegeBox_2.setEnabled(True)
        self.collegeBox_2.setGeometry(QtCore.QRect(488, 140, 311, 26))
        self.collegeBox_2.setObjectName("collegeBox_2")
        self.collegeBox_2.addItem("")
        self.collegeBox_2.addItem("")
        self.collegeBox_2.addItem("")
        self.collegeBox_2.addItem("")
        self.collegeBox_2.addItem("")
        self.collegeBox_2.addItem("")
        self.collegeBox_2.addItem("")
        self.collegeBox_2.addItem("")
        self.collegeBox_2.addItem("")
        self.collegeBox_2.addItem("")
        self.collegeBox_2.addItem("")
        self.collegeBox_2.addItem("")
        self.collegeBox_2.addItem("")
        self.minorCollege = QtWidgets.QLabel(Form)
        self.minorCollege.setGeometry(QtCore.QRect(30, 230, 101, 16))
        self.minorCollege.setObjectName("minorCollege")
        self.minorCollegeBox1 = QtWidgets.QComboBox(Form)
        self.minorCollegeBox1.setEnabled(True)
        self.minorCollegeBox1.setGeometry(QtCore.QRect(170, 220, 311, 26))
        self.minorCollegeBox1.setObjectName("minorCollegeBox1")
        self.minorCollegeBox1.addItem("")
        self.minorCollegeBox1.addItem("")
        self.minorCollegeBox1.addItem("")
        self.minorCollegeBox1.addItem("")
        self.minorCollegeBox1.addItem("")
        self.minorCollegeBox1.addItem("")
        self.minorCollegeBox1.addItem("")
        self.minorCollegeBox1.addItem("")
        self.minorCollegeBox1.addItem("")
        self.minorCollegeBox1.addItem("")
        self.minorCollegeBox1.addItem("")
        self.minorCollegeBox1.addItem("")
        self.minorCollegeBox1.addItem("")
        self.minorCollegeBox2 = QtWidgets.QComboBox(Form)
        self.minorCollegeBox2.setEnabled(True)
        self.minorCollegeBox2.setGeometry(QtCore.QRect(488, 220, 311, 26))
        self.minorCollegeBox2.setObjectName("minorCollegeBox2")
        self.minorCollegeBox2.addItem("")
        self.minorCollegeBox2.addItem("")
        self.minorCollegeBox2.addItem("")
        self.minorCollegeBox2.addItem("")
        self.minorCollegeBox2.addItem("")
        self.minorCollegeBox2.addItem("")
        self.minorCollegeBox2.addItem("")
        self.minorCollegeBox2.addItem("")
        self.minorCollegeBox2.addItem("")
        self.minorCollegeBox2.addItem("")
        self.minorCollegeBox2.addItem("")
        self.minorCollegeBox2.addItem("")
        self.minorCollegeBox2.addItem("")
        self.scholar = QtWidgets.QLabel(Form)
        self.scholar.setGeometry(QtCore.QRect(30, 360, 121, 16))
        self.scholar.setObjectName("scholar")
        self.honorsCheck = QtWidgets.QCheckBox(Form)
        self.honorsCheck.setGeometry(QtCore.QRect(170, 360, 171, 20))
        self.honorsCheck.setObjectName("honorsCheck")
        self.presidents = QtWidgets.QCheckBox(Form)
        self.presidents.setGeometry(QtCore.QRect(170, 400, 521, 21))
        self.presidents.setObjectName("presidents")
        self.mcnair = QtWidgets.QCheckBox(Form)
        self.mcnair.setGeometry(QtCore.QRect(170, 380, 121, 20))
        self.mcnair.setObjectName("mcnair")
        self.sstem = QtWidgets.QCheckBox(Form)
        self.sstem.setGeometry(QtCore.QRect(290, 380, 121, 20))
        self.sstem.setObjectName("sstem")
        self.laSTEM = QtWidgets.QCheckBox(Form)
        self.laSTEM.setGeometry(QtCore.QRect(350, 360, 181, 20))
        self.laSTEM.setObjectName("laSTEM")
        self.aspire = QtWidgets.QCheckBox(Form)
        self.aspire.setGeometry(QtCore.QRect(420, 380, 121, 20))
        self.aspire.setObjectName("aspire")
        self.previously = QtWidgets.QLabel(Form)
        self.previously.setGeometry(QtCore.QRect(190, 420, 321, 16))
        self.previously.setObjectName("previously")
        self.reu = QtWidgets.QCheckBox(Form)
        self.reu.setGeometry(QtCore.QRect(170, 440, 171, 20))
        self.reu.setObjectName("reu")
        self.other = QtWidgets.QCheckBox(Form)
        self.other.setGeometry(QtCore.QRect(350, 440, 87, 20))
        self.other.setObjectName("other")
        self.mentorEmailBox2 = QtWidgets.QLineEdit(Form)
        self.mentorEmailBox2.setGeometry(QtCore.QRect(580, 320, 191, 21))
        self.mentorEmailBox2.setObjectName("mentorEmailBox2")
        self.mentor2 = QtWidgets.QLabel(Form)
        self.mentor2.setGeometry(QtCore.QRect(31, 326, 71, 16))
        self.mentor2.setObjectName("mentor2")
        self.mentorEmail2 = QtWidgets.QLabel(Form)
        self.mentorEmail2.setGeometry(QtCore.QRect(480, 320, 101, 16))
        self.mentorEmail2.setObjectName("mentorEmail2")
        self.mentorLast2 = QtWidgets.QLabel(Form)
        self.mentorLast2.setGeometry(QtCore.QRect(330, 340, 26, 16))
        self.mentorLast2.setObjectName("mentorLast2")
        self.mentorFirstBox2 = QtWidgets.QLineEdit(Form)
        self.mentorFirstBox2.setGeometry(QtCore.QRect(174, 319, 131, 21))
        self.mentorFirstBox2.setObjectName("mentorFirstBox2")
        self.mentorLastBox2 = QtWidgets.QLineEdit(Form)
        self.mentorLastBox2.setGeometry(QtCore.QRect(326, 319, 131, 21))
        self.mentorLastBox2.setObjectName("mentorLastBox2")
        self.mentorFirst2 = QtWidgets.QLabel(Form)
        self.mentorFirst2.setGeometry(QtCore.QRect(180, 340, 27, 16))
        self.mentorFirst2.setObjectName("mentorFirst2")
        self.antiFall = QtWidgets.QCheckBox(Form)
        self.antiFall.setGeometry(QtCore.QRect(170, 490, 41, 20))
        self.antiFall.setObjectName("antiFall")
        self.antiSpring = QtWidgets.QCheckBox(Form)
        self.antiSpring.setGeometry(QtCore.QRect(220, 490, 61, 20))
        self.antiSpring.setObjectName("antiSpring")
        self.antiSummer = QtWidgets.QCheckBox(Form)
        self.antiSummer.setGeometry(QtCore.QRect(290, 490, 71, 20))
        self.antiSummer.setObjectName("antiSummer")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(370, 490, 90, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gradSpring = QtWidgets.QCheckBox(Form)
        self.gradSpring.setGeometry(QtCore.QRect(220, 520, 61, 20))
        self.gradSpring.setObjectName("gradSpring")
        self.gradFall = QtWidgets.QCheckBox(Form)
        self.gradFall.setGeometry(QtCore.QRect(170, 520, 41, 20))
        self.gradFall.setObjectName("gradFall")
        self.gradSummer = QtWidgets.QCheckBox(Form)
        self.gradSummer.setGeometry(QtCore.QRect(290, 520, 71, 20))
        self.gradSummer.setObjectName("gradSummer")
        self.gradYear2 = QtWidgets.QComboBox(Form)
        self.gradYear2.setGeometry(QtCore.QRect(370, 520, 90, 26))
        self.gradYear2.setObjectName("gradYear2")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.gradYear2.addItem("")
        self.majorDropdown2 = QtWidgets.QComboBox(Form)
        self.majorDropdown2.setGeometry(QtCore.QRect(490, 170, 311, 26))
        self.majorDropdown2.setObjectName("majorDropdown2")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.majorDropdown2.addItem("")
        self.minorDropdown1 = QtWidgets.QComboBox(Form)
        self.minorDropdown1.setGeometry(QtCore.QRect(490, 250, 311, 26))
        self.minorDropdown1.setObjectName("minorDropdown1")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown1.addItem("")
        self.minorDropdown2 = QtWidgets.QComboBox(Form)
        self.minorDropdown2.setGeometry(QtCore.QRect(170, 250, 311, 26))
        self.minorDropdown2.setObjectName("minorDropdown2")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.minorDropdown2.addItem("")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(490, 120, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(490, 200, 91, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addStudent.setText(_translate("Form", "Student Information"))
        self.student.setText(_translate("Form", "Student"))
        self.mentorLast.setText(_translate("Form", "Last"))
        self.studentFirst.setText(_translate("Form", "First"))
        self.mentor.setText(_translate("Form", "Mentor (1)"))
        self.studentEmail.setText(_translate("Form", "Username (Email)"))
        self.majors.setText(_translate("Form", "Major(s)"))
        self.minors.setText(_translate("Form", "Minor(s)"))
        self.mentorEmail.setText(_translate("Form", "Mentor Email"))
        self.antiGradDate.setText(_translate("Form", "Anticipated Grad Date"))
        self.gradDate.setText(_translate("Form", "Graduation Date"))
        self.durp.setText(_translate("Form", "DURP status"))
        self.lsuEdu.setText(_translate("Form", "@lsu.edu"))
        self.mentorFirst.setText(_translate("Form", "First"))
        self.studentLast.setText(_translate("Form", "Last"))
        self.durpDropdown.setItemText(0, _translate("Form", "select one:"))
        self.durpDropdown.setItemText(1, _translate("Form", "Candidate"))
        self.durpDropdown.setItemText(2, _translate("Form", "Awardee"))
        self.durpDropdown.setItemText(3, _translate("Form", "Not enrolled"))
        self.collegeBox.setItemText(0, _translate("Form", "Select One:"))
        self.collegeBox.setItemText(1, _translate("Form", "College of Agriculture"))
        self.collegeBox.setItemText(2, _translate("Form", "College of Art and Design"))
        self.collegeBox.setItemText(3, _translate("Form", "E.J. Ourso College of Business"))
        self.collegeBox.setItemText(4, _translate("Form", "College of the Coast & Environment"))
        self.collegeBox.setItemText(5, _translate("Form", "College of Engineering"))
        self.collegeBox.setItemText(6, _translate("Form", "College of Human Sciences & Education"))
        self.collegeBox.setItemText(7, _translate("Form", "College of Humanities & Social Sciences"))
        self.collegeBox.setItemText(8, _translate("Form", "Manship School of Mass Communication"))
        self.collegeBox.setItemText(9, _translate("Form", "College of Music & Dramatic Arts"))
        self.collegeBox.setItemText(10, _translate("Form", "College of Science"))
        self.collegeBox.setItemText(11, _translate("Form", "Ogden Honors College"))
        self.collegeBox.setItemText(12, _translate("Form", "University College Center for Freshman Year"))
        self.college.setText(_translate("Form", "Major College(s)"))
        self.entryLabel.setText(_translate("Form", "Entry Completed on"))
        self.majorDropdown.setItemText(0, _translate("Form", "Select One:"))
        self.majorDropdown.setItemText(1, _translate("Form", "AG - Agricultural Economics and Agribusiness"))
        self.majorDropdown.setItemText(2, _translate("Form", "AG - Agricultural Extension, Education and Evaluation"))
        self.majorDropdown.setItemText(3, _translate("Form", "AG - Animal Sciences"))
        self.majorDropdown.setItemText(4, _translate("Form", "AG - Entomology"))
        self.majorDropdown.setItemText(5, _translate("Form", "AG - Experimental Statitics"))
        self.majorDropdown.setItemText(6, _translate("Form", "AG - Nutrition and Food Sciences"))
        self.majorDropdown.setItemText(7, _translate("Form", "AG - Plant, Environmental, and Soil Sciences"))
        self.majorDropdown.setItemText(8, _translate("Form", "AG - Plant Pathology and Crop Physiology"))
        self.majorDropdown.setItemText(9, _translate("Form", "AG - Renewable Natural Resources"))
        self.majorDropdown.setItemText(10, _translate("Form", "AG - Textiles, Apparel Design, and Merchandising"))
        self.majorDropdown.setItemText(11, _translate("Form", "ART - Architecture"))
        self.majorDropdown.setItemText(12, _translate("Form", "ART - Art"))
        self.majorDropdown.setItemText(13, _translate("Form", "ART - Interior Design"))
        self.majorDropdown.setItemText(14, _translate("Form", "ART - Landscape Architecture"))
        self.majorDropdown.setItemText(15, _translate("Form", "BUS - Accounting"))
        self.majorDropdown.setItemText(16, _translate("Form", "BUS - Economics"))
        self.majorDropdown.setItemText(17, _translate("Form", "BUS - FInance"))
        self.majorDropdown.setItemText(18, _translate("Form", "BUS - ISDS"))
        self.majorDropdown.setItemText(19, _translate("Form", "BUS - Management"))
        self.majorDropdown.setItemText(20, _translate("Form", "BUS - Marketing"))
        self.majorDropdown.setItemText(21, _translate("Form", "COAST - Environmental Sciences"))
        self.majorDropdown.setItemText(22, _translate("Form", "COAST - Oceanography & Coastal Sciences"))
        self.majorDropdown.setItemText(23, _translate("Form", "ENG - Biological Engineering"))
        self.majorDropdown.setItemText(24, _translate("Form", "ENG - Chemical Engineering"))
        self.majorDropdown.setItemText(25, _translate("Form", "ENG - Civil Engineering"))
        self.majorDropdown.setItemText(26, _translate("Form", "ENG - Construction Management"))
        self.majorDropdown.setItemText(27, _translate("Form", "ENG - Computer Engineering"))
        self.majorDropdown.setItemText(28, _translate("Form", "ENG - Electrical Engineering"))
        self.majorDropdown.setItemText(29, _translate("Form", "ENG - Environmental Engineering"))
        self.majorDropdown.setItemText(30, _translate("Form", "ENG - Industrial Engineering"))
        self.majorDropdown.setItemText(31, _translate("Form", "ENG - Mechanical Engineering"))
        self.majorDropdown.setItemText(32, _translate("Form", "ENG - Petroleum Engineering"))
        self.majorDropdown.setItemText(33, _translate("Form", "HSE - Education"))
        self.majorDropdown.setItemText(34, _translate("Form", "HSE - Human Resource Education & Workforce Development"))
        self.majorDropdown.setItemText(35, _translate("Form", "HSE - Kinesiology"))
        self.majorDropdown.setItemText(36, _translate("Form", "HSE - Library & Information Sciences"))
        self.majorDropdown.setItemText(37, _translate("Form", "HSE - Social Work"))
        self.majorDropdown.setItemText(38, _translate("Form", "HSS - Aerospace Studies"))
        self.majorDropdown.setItemText(39, _translate("Form", "HSS - Communication Sciences & Disorders"))
        self.majorDropdown.setItemText(40, _translate("Form", "HSS - Communication Studies"))
        self.majorDropdown.setItemText(41, _translate("Form", "HSS - English"))
        self.majorDropdown.setItemText(42, _translate("Form", "HSS - Foreign Languages & Literatures"))
        self.majorDropdown.setItemText(43, _translate("Form", "HSS - French Studies"))
        self.majorDropdown.setItemText(44, _translate("Form", "HSS - Geography & Anthropology"))
        self.majorDropdown.setItemText(45, _translate("Form", "HSS - History"))
        self.majorDropdown.setItemText(46, _translate("Form", "HSS - Military Science"))
        self.majorDropdown.setItemText(47, _translate("Form", "HSS - Philosophy & Religious Studies"))
        self.majorDropdown.setItemText(48, _translate("Form", "HSS - Psychology"))
        self.majorDropdown.setItemText(49, _translate("Form", "HSS - Sociology"))
        self.majorDropdown.setItemText(50, _translate("Form", "MCOMM - Journalism"))
        self.majorDropdown.setItemText(51, _translate("Form", "MCOMM - Digital Advertising"))
        self.majorDropdown.setItemText(52, _translate("Form", "MCOMM - Political Communication"))
        self.majorDropdown.setItemText(53, _translate("Form", "MCOMM - Public Relations"))
        self.majorDropdown.setItemText(54, _translate("Form", "MDA - Music"))
        self.majorDropdown.setItemText(55, _translate("Form", "MDA - Theatre"))
        self.majorDropdown.setItemText(56, _translate("Form", "SCI - Biological Sciences"))
        self.majorDropdown.setItemText(57, _translate("Form", "SCI - Chemistry"))
        self.majorDropdown.setItemText(58, _translate("Form", "SCI - Geology & Geophysics"))
        self.majorDropdown.setItemText(59, _translate("Form", "SCI - Mathematics"))
        self.majorDropdown.setItemText(60, _translate("Form", "SCI - Physics & Astronomy"))
        self.majorDropdown.setItemText(61, _translate("Form", "SCI - Natural Science"))
        self.majorDropdown.setItemText(62, _translate("Form", "Undecided - Arts & Humanities"))
        self.majorDropdown.setItemText(63, _translate("Form", "Undecided - Science & Engineering"))
        self.majorDropdown.setItemText(64, _translate("Form", "Undecided - Social Science"))
        self.majorDropdown.setItemText(65, _translate("Form", "Other"))
        self.collegeBox_2.setItemText(0, _translate("Form", "Select One:"))
        self.collegeBox_2.setItemText(1, _translate("Form", "College of Agriculture"))
        self.collegeBox_2.setItemText(2, _translate("Form", "College of Art and Design"))
        self.collegeBox_2.setItemText(3, _translate("Form", "E.J. Ourso College of Business"))
        self.collegeBox_2.setItemText(4, _translate("Form", "College of the Coast & Environment"))
        self.collegeBox_2.setItemText(5, _translate("Form", "College of Engineering"))
        self.collegeBox_2.setItemText(6, _translate("Form", "College of Human Sciences & Education"))
        self.collegeBox_2.setItemText(7, _translate("Form", "College of Humanities & Social Sciences"))
        self.collegeBox_2.setItemText(8, _translate("Form", "Manship School of Mass Communication"))
        self.collegeBox_2.setItemText(9, _translate("Form", "College of Music & Dramatic Arts"))
        self.collegeBox_2.setItemText(10, _translate("Form", "College of Science"))
        self.collegeBox_2.setItemText(11, _translate("Form", "Ogden Honors College"))
        self.collegeBox_2.setItemText(12, _translate("Form", "University College Center for Freshman Year"))
        self.minorCollege.setText(_translate("Form", "Minor College(s)"))
        self.minorCollegeBox1.setItemText(0, _translate("Form", "Select One:"))
        self.minorCollegeBox1.setItemText(1, _translate("Form", "College of Agriculture"))
        self.minorCollegeBox1.setItemText(2, _translate("Form", "College of Art and Design"))
        self.minorCollegeBox1.setItemText(3, _translate("Form", "E.J. Ourso College of Business"))
        self.minorCollegeBox1.setItemText(4, _translate("Form", "College of the Coast & Environment"))
        self.minorCollegeBox1.setItemText(5, _translate("Form", "College of Engineering"))
        self.minorCollegeBox1.setItemText(6, _translate("Form", "College of Human Sciences & Education"))
        self.minorCollegeBox1.setItemText(7, _translate("Form", "College of Humanities & Social Sciences"))
        self.minorCollegeBox1.setItemText(8, _translate("Form", "Manship School of Mass Communication"))
        self.minorCollegeBox1.setItemText(9, _translate("Form", "College of Music & Dramatic Arts"))
        self.minorCollegeBox1.setItemText(10, _translate("Form", "College of Science"))
        self.minorCollegeBox1.setItemText(11, _translate("Form", "Ogden Honors College"))
        self.minorCollegeBox1.setItemText(12, _translate("Form", "University College Center for Freshman Year"))
        self.minorCollegeBox2.setItemText(0, _translate("Form", "Select One:"))
        self.minorCollegeBox2.setItemText(1, _translate("Form", "College of Agriculture"))
        self.minorCollegeBox2.setItemText(2, _translate("Form", "College of Art and Design"))
        self.minorCollegeBox2.setItemText(3, _translate("Form", "E.J. Ourso College of Business"))
        self.minorCollegeBox2.setItemText(4, _translate("Form", "College of the Coast & Environment"))
        self.minorCollegeBox2.setItemText(5, _translate("Form", "College of Engineering"))
        self.minorCollegeBox2.setItemText(6, _translate("Form", "College of Human Sciences & Education"))
        self.minorCollegeBox2.setItemText(7, _translate("Form", "College of Humanities & Social Sciences"))
        self.minorCollegeBox2.setItemText(8, _translate("Form", "Manship School of Mass Communication"))
        self.minorCollegeBox2.setItemText(9, _translate("Form", "College of Music & Dramatic Arts"))
        self.minorCollegeBox2.setItemText(10, _translate("Form", "College of Science"))
        self.minorCollegeBox2.setItemText(11, _translate("Form", "Ogden Honors College"))
        self.minorCollegeBox2.setItemText(12, _translate("Form", "University College Center for Freshman Year"))
        self.scholar.setText(_translate("Form", "Scholar Affiliations:"))
        self.honorsCheck.setText(_translate("Form", "Honors College Student"))
        self.presidents.setText(_translate("Form", "President\'s Future Leaders in Research"))
        self.mcnair.setText(_translate("Form", "McNair Scholar"))
        self.sstem.setText(_translate("Form", "S-STEM Scholar"))
        self.laSTEM.setText(_translate("Form", "LaSTEM Reseach Scholar"))
        self.aspire.setText(_translate("Form", "ASPIRE Student"))
        self.previously.setText(_translate("Form", "(Previously Chancellor\'s Future Leaders in Research)"))
        self.reu.setText(_translate("Form", "REU summer researcher"))
        self.other.setText(_translate("Form", "Other"))
        self.mentor2.setText(_translate("Form", "Mentor (2)"))
        self.mentorEmail2.setText(_translate("Form", "Mentor Email"))
        self.mentorLast2.setText(_translate("Form", "Last"))
        self.mentorFirst2.setText(_translate("Form", "First"))
        self.antiFall.setText(_translate("Form", "Fall"))
        self.antiSpring.setText(_translate("Form", "Spring"))
        self.antiSummer.setText(_translate("Form", "Summer"))
        self.comboBox.setItemText(0, _translate("Form", "Year"))
        self.comboBox.setItemText(1, _translate("Form", "2015"))
        self.comboBox.setItemText(2, _translate("Form", "2016"))
        self.comboBox.setItemText(3, _translate("Form", "2017"))
        self.comboBox.setItemText(4, _translate("Form", "2018"))
        self.comboBox.setItemText(5, _translate("Form", "2019"))
        self.comboBox.setItemText(6, _translate("Form", "2020"))
        self.comboBox.setItemText(7, _translate("Form", "2021"))
        self.comboBox.setItemText(8, _translate("Form", "2022"))
        self.comboBox.setItemText(9, _translate("Form", "2023"))
        self.comboBox.setItemText(10, _translate("Form", "2024"))
        self.comboBox.setItemText(11, _translate("Form", "2025"))
        self.comboBox.setItemText(12, _translate("Form", "2026"))
        self.comboBox.setItemText(13, _translate("Form", "2027"))
        self.comboBox.setItemText(14, _translate("Form", "2028"))
        self.comboBox.setItemText(15, _translate("Form", "2029"))
        self.comboBox.setItemText(16, _translate("Form", "2030"))
        self.comboBox.setItemText(17, _translate("Form", "2031"))
        self.comboBox.setItemText(18, _translate("Form", "2032"))
        self.comboBox.setItemText(19, _translate("Form", "2033"))
        self.comboBox.setItemText(20, _translate("Form", "2034"))
        self.comboBox.setItemText(21, _translate("Form", "2035"))
        self.comboBox.setItemText(22, _translate("Form", "2036"))
        self.comboBox.setItemText(23, _translate("Form", "2037"))
        self.comboBox.setItemText(24, _translate("Form", "2038"))
        self.comboBox.setItemText(25, _translate("Form", "2039"))
        self.comboBox.setItemText(26, _translate("Form", "2040"))
        self.gradSpring.setText(_translate("Form", "Spring"))
        self.gradFall.setText(_translate("Form", "Fall"))
        self.gradSummer.setText(_translate("Form", "Summer"))
        self.gradYear2.setItemText(0, _translate("Form", "Year"))
        self.gradYear2.setItemText(1, _translate("Form", "2015"))
        self.gradYear2.setItemText(2, _translate("Form", "2016"))
        self.gradYear2.setItemText(3, _translate("Form", "2017"))
        self.gradYear2.setItemText(4, _translate("Form", "2018"))
        self.gradYear2.setItemText(5, _translate("Form", "2019"))
        self.gradYear2.setItemText(6, _translate("Form", "2020"))
        self.gradYear2.setItemText(7, _translate("Form", "2021"))
        self.gradYear2.setItemText(8, _translate("Form", "2022"))
        self.gradYear2.setItemText(9, _translate("Form", "2023"))
        self.gradYear2.setItemText(10, _translate("Form", "2024"))
        self.gradYear2.setItemText(11, _translate("Form", "2025"))
        self.gradYear2.setItemText(12, _translate("Form", "2026"))
        self.gradYear2.setItemText(13, _translate("Form", "2027"))
        self.gradYear2.setItemText(14, _translate("Form", "2028"))
        self.gradYear2.setItemText(15, _translate("Form", "2029"))
        self.gradYear2.setItemText(16, _translate("Form", "2030"))
        self.gradYear2.setItemText(17, _translate("Form", "2031"))
        self.gradYear2.setItemText(18, _translate("Form", "2032"))
        self.gradYear2.setItemText(19, _translate("Form", "2033"))
        self.gradYear2.setItemText(20, _translate("Form", "2034"))
        self.gradYear2.setItemText(21, _translate("Form", "2035"))
        self.gradYear2.setItemText(22, _translate("Form", "2036"))
        self.gradYear2.setItemText(23, _translate("Form", "2037"))
        self.gradYear2.setItemText(24, _translate("Form", "2038"))
        self.gradYear2.setItemText(25, _translate("Form", "2039"))
        self.gradYear2.setItemText(26, _translate("Form", "2040"))
        self.majorDropdown2.setItemText(0, _translate("Form", "Select One:"))
        self.majorDropdown2.setItemText(1, _translate("Form", "AG - Agricultural Economics and Agribusiness"))
        self.majorDropdown2.setItemText(2, _translate("Form", "AG - Agricultural Extension, Education and Evaluation"))
        self.majorDropdown2.setItemText(3, _translate("Form", "AG - Animal Sciences"))
        self.majorDropdown2.setItemText(4, _translate("Form", "AG - Entomology"))
        self.majorDropdown2.setItemText(5, _translate("Form", "AG - Experimental Statitics"))
        self.majorDropdown2.setItemText(6, _translate("Form", "AG - Nutrition and Food Sciences"))
        self.majorDropdown2.setItemText(7, _translate("Form", "AG - Plant, Environmental, and Soil Sciences"))
        self.majorDropdown2.setItemText(8, _translate("Form", "AG - Plant Pathology and Crop Physiology"))
        self.majorDropdown2.setItemText(9, _translate("Form", "AG - Renewable Natural Resources"))
        self.majorDropdown2.setItemText(10, _translate("Form", "AG - Textiles, Apparel Design, and Merchandising"))
        self.majorDropdown2.setItemText(11, _translate("Form", "ART - Architecture"))
        self.majorDropdown2.setItemText(12, _translate("Form", "ART - Art"))
        self.majorDropdown2.setItemText(13, _translate("Form", "ART - Interior Design"))
        self.majorDropdown2.setItemText(14, _translate("Form", "ART - Landscape Architecture"))
        self.majorDropdown2.setItemText(15, _translate("Form", "BUS - Accounting"))
        self.majorDropdown2.setItemText(16, _translate("Form", "BUS - Economics"))
        self.majorDropdown2.setItemText(17, _translate("Form", "BUS - FInance"))
        self.majorDropdown2.setItemText(18, _translate("Form", "BUS - ISDS"))
        self.majorDropdown2.setItemText(19, _translate("Form", "BUS - Management"))
        self.majorDropdown2.setItemText(20, _translate("Form", "BUS - Marketing"))
        self.majorDropdown2.setItemText(21, _translate("Form", "COAST - Environmental Sciences"))
        self.majorDropdown2.setItemText(22, _translate("Form", "COAST - Oceanography & Coastal Sciences"))
        self.majorDropdown2.setItemText(23, _translate("Form", "ENG - Biological Engineering"))
        self.majorDropdown2.setItemText(24, _translate("Form", "ENG - Chemical Engineering"))
        self.majorDropdown2.setItemText(25, _translate("Form", "ENG - Civil Engineering"))
        self.majorDropdown2.setItemText(26, _translate("Form", "ENG - Construction Management"))
        self.majorDropdown2.setItemText(27, _translate("Form", "ENG - Computer Engineering"))
        self.majorDropdown2.setItemText(28, _translate("Form", "ENG - Electrical Engineering"))
        self.majorDropdown2.setItemText(29, _translate("Form", "ENG - Environmental Engineering"))
        self.majorDropdown2.setItemText(30, _translate("Form", "ENG - Industrial Engineering"))
        self.majorDropdown2.setItemText(31, _translate("Form", "ENG - Mechanical Engineering"))
        self.majorDropdown2.setItemText(32, _translate("Form", "ENG - Petroleum Engineering"))
        self.majorDropdown2.setItemText(33, _translate("Form", "HSE - Education"))
        self.majorDropdown2.setItemText(34, _translate("Form", "HSE - Human Resource Education & Workforce Development"))
        self.majorDropdown2.setItemText(35, _translate("Form", "HSE - Kinesiology"))
        self.majorDropdown2.setItemText(36, _translate("Form", "HSE - Library & Information Sciences"))
        self.majorDropdown2.setItemText(37, _translate("Form", "HSE - Social Work"))
        self.majorDropdown2.setItemText(38, _translate("Form", "HSS - Aerospace Studies"))
        self.majorDropdown2.setItemText(39, _translate("Form", "HSS - Communication Sciences & Disorders"))
        self.majorDropdown2.setItemText(40, _translate("Form", "HSS - Communication Studies"))
        self.majorDropdown2.setItemText(41, _translate("Form", "HSS - English"))
        self.majorDropdown2.setItemText(42, _translate("Form", "HSS - Foreign Languages & Literatures"))
        self.majorDropdown2.setItemText(43, _translate("Form", "HSS - French Studies"))
        self.majorDropdown2.setItemText(44, _translate("Form", "HSS - Geography & Anthropology"))
        self.majorDropdown2.setItemText(45, _translate("Form", "HSS - History"))
        self.majorDropdown2.setItemText(46, _translate("Form", "HSS - Military Science"))
        self.majorDropdown2.setItemText(47, _translate("Form", "HSS - Philosophy & Religious Studies"))
        self.majorDropdown2.setItemText(48, _translate("Form", "HSS - Psychology"))
        self.majorDropdown2.setItemText(49, _translate("Form", "HSS - Sociology"))
        self.majorDropdown2.setItemText(50, _translate("Form", "MCOMM - Journalism"))
        self.majorDropdown2.setItemText(51, _translate("Form", "MCOMM - Digital Advertising"))
        self.majorDropdown2.setItemText(52, _translate("Form", "MCOMM - Political Communication"))
        self.majorDropdown2.setItemText(53, _translate("Form", "MCOMM - Public Relations"))
        self.majorDropdown2.setItemText(54, _translate("Form", "MDA - Music"))
        self.majorDropdown2.setItemText(55, _translate("Form", "MDA - Theatre"))
        self.majorDropdown2.setItemText(56, _translate("Form", "SCI - Biological Sciences"))
        self.majorDropdown2.setItemText(57, _translate("Form", "SCI - Chemistry"))
        self.majorDropdown2.setItemText(58, _translate("Form", "SCI - Geology & Geophysics"))
        self.majorDropdown2.setItemText(59, _translate("Form", "SCI - Mathematics"))
        self.majorDropdown2.setItemText(60, _translate("Form", "SCI - Physics & Astronomy"))
        self.majorDropdown2.setItemText(61, _translate("Form", "SCI - Natural Science"))
        self.majorDropdown2.setItemText(62, _translate("Form", "Undecided - Arts & Humanities"))
        self.majorDropdown2.setItemText(63, _translate("Form", "Undecided - Science & Engineering"))
        self.majorDropdown2.setItemText(64, _translate("Form", "Undecided - Social Science"))
        self.majorDropdown2.setItemText(65, _translate("Form", "Other"))
        self.minorDropdown1.setItemText(0, _translate("Form", "Select One:"))
        self.minorDropdown1.setItemText(1, _translate("Form", "AG - Agricultural Economics and Agribusiness"))
        self.minorDropdown1.setItemText(2, _translate("Form", "AG - Agricultural Extension, Education and Evaluation"))
        self.minorDropdown1.setItemText(3, _translate("Form", "AG - Animal Sciences"))
        self.minorDropdown1.setItemText(4, _translate("Form", "AG - Entomology"))
        self.minorDropdown1.setItemText(5, _translate("Form", "AG - Experimental Statitics"))
        self.minorDropdown1.setItemText(6, _translate("Form", "AG - Nutrition and Food Sciences"))
        self.minorDropdown1.setItemText(7, _translate("Form", "AG - Plant, Environmental, and Soil Sciences"))
        self.minorDropdown1.setItemText(8, _translate("Form", "AG - Plant Pathology and Crop Physiology"))
        self.minorDropdown1.setItemText(9, _translate("Form", "AG - Renewable Natural Resources"))
        self.minorDropdown1.setItemText(10, _translate("Form", "AG - Textiles, Apparel Design, and Merchandising"))
        self.minorDropdown1.setItemText(11, _translate("Form", "ART - Architecture"))
        self.minorDropdown1.setItemText(12, _translate("Form", "ART - Art"))
        self.minorDropdown1.setItemText(13, _translate("Form", "ART - Interior Design"))
        self.minorDropdown1.setItemText(14, _translate("Form", "ART - Landscape Architecture"))
        self.minorDropdown1.setItemText(15, _translate("Form", "BUS - Accounting"))
        self.minorDropdown1.setItemText(16, _translate("Form", "BUS - Economics"))
        self.minorDropdown1.setItemText(17, _translate("Form", "BUS - FInance"))
        self.minorDropdown1.setItemText(18, _translate("Form", "BUS - ISDS"))
        self.minorDropdown1.setItemText(19, _translate("Form", "BUS - Management"))
        self.minorDropdown1.setItemText(20, _translate("Form", "BUS - Marketing"))
        self.minorDropdown1.setItemText(21, _translate("Form", "COAST - Environmental Sciences"))
        self.minorDropdown1.setItemText(22, _translate("Form", "COAST - Oceanography & Coastal Sciences"))
        self.minorDropdown1.setItemText(23, _translate("Form", "ENG - Biological Engineering"))
        self.minorDropdown1.setItemText(24, _translate("Form", "ENG - Chemical Engineering"))
        self.minorDropdown1.setItemText(25, _translate("Form", "ENG - Civil Engineering"))
        self.minorDropdown1.setItemText(26, _translate("Form", "ENG - Construction Management"))
        self.minorDropdown1.setItemText(27, _translate("Form", "ENG - Computer Engineering"))
        self.minorDropdown1.setItemText(28, _translate("Form", "ENG - Electrical Engineering"))
        self.minorDropdown1.setItemText(29, _translate("Form", "ENG - Environmental Engineering"))
        self.minorDropdown1.setItemText(30, _translate("Form", "ENG - Industrial Engineering"))
        self.minorDropdown1.setItemText(31, _translate("Form", "ENG - Mechanical Engineering"))
        self.minorDropdown1.setItemText(32, _translate("Form", "ENG - Petroleum Engineering"))
        self.minorDropdown1.setItemText(33, _translate("Form", "HSE - Education"))
        self.minorDropdown1.setItemText(34, _translate("Form", "HSE - Human Resource Education & Workforce Development"))
        self.minorDropdown1.setItemText(35, _translate("Form", "HSE - Kinesiology"))
        self.minorDropdown1.setItemText(36, _translate("Form", "HSE - Library & Information Sciences"))
        self.minorDropdown1.setItemText(37, _translate("Form", "HSE - Social Work"))
        self.minorDropdown1.setItemText(38, _translate("Form", "HSS - Aerospace Studies"))
        self.minorDropdown1.setItemText(39, _translate("Form", "HSS - Communication Sciences & Disorders"))
        self.minorDropdown1.setItemText(40, _translate("Form", "HSS - Communication Studies"))
        self.minorDropdown1.setItemText(41, _translate("Form", "HSS - English"))
        self.minorDropdown1.setItemText(42, _translate("Form", "HSS - Foreign Languages & Literatures"))
        self.minorDropdown1.setItemText(43, _translate("Form", "HSS - French Studies"))
        self.minorDropdown1.setItemText(44, _translate("Form", "HSS - Geography & Anthropology"))
        self.minorDropdown1.setItemText(45, _translate("Form", "HSS - History"))
        self.minorDropdown1.setItemText(46, _translate("Form", "HSS - Military Science"))
        self.minorDropdown1.setItemText(47, _translate("Form", "HSS - Philosophy & Religious Studies"))
        self.minorDropdown1.setItemText(48, _translate("Form", "HSS - Psychology"))
        self.minorDropdown1.setItemText(49, _translate("Form", "HSS - Sociology"))
        self.minorDropdown1.setItemText(50, _translate("Form", "MCOMM - Journalism"))
        self.minorDropdown1.setItemText(51, _translate("Form", "MCOMM - Digital Advertising"))
        self.minorDropdown1.setItemText(52, _translate("Form", "MCOMM - Political Communication"))
        self.minorDropdown1.setItemText(53, _translate("Form", "MCOMM - Public Relations"))
        self.minorDropdown1.setItemText(54, _translate("Form", "MDA - Music"))
        self.minorDropdown1.setItemText(55, _translate("Form", "MDA - Theatre"))
        self.minorDropdown1.setItemText(56, _translate("Form", "SCI - Biological Sciences"))
        self.minorDropdown1.setItemText(57, _translate("Form", "SCI - Chemistry"))
        self.minorDropdown1.setItemText(58, _translate("Form", "SCI - Geology & Geophysics"))
        self.minorDropdown1.setItemText(59, _translate("Form", "SCI - Mathematics"))
        self.minorDropdown1.setItemText(60, _translate("Form", "SCI - Physics & Astronomy"))
        self.minorDropdown1.setItemText(61, _translate("Form", "SCI - Natural Science"))
        self.minorDropdown1.setItemText(62, _translate("Form", "Undecided - Arts & Humanities"))
        self.minorDropdown1.setItemText(63, _translate("Form", "Undecided - Science & Engineering"))
        self.minorDropdown1.setItemText(64, _translate("Form", "Undecided - Social Science"))
        self.minorDropdown1.setItemText(65, _translate("Form", "Other"))
        self.minorDropdown2.setItemText(0, _translate("Form", "Select One:"))
        self.minorDropdown2.setItemText(1, _translate("Form", "AG - Agricultural Economics and Agribusiness"))
        self.minorDropdown2.setItemText(2, _translate("Form", "AG - Agricultural Extension, Education and Evaluation"))
        self.minorDropdown2.setItemText(3, _translate("Form", "AG - Animal Sciences"))
        self.minorDropdown2.setItemText(4, _translate("Form", "AG - Entomology"))
        self.minorDropdown2.setItemText(5, _translate("Form", "AG - Experimental Statitics"))
        self.minorDropdown2.setItemText(6, _translate("Form", "AG - Nutrition and Food Sciences"))
        self.minorDropdown2.setItemText(7, _translate("Form", "AG - Plant, Environmental, and Soil Sciences"))
        self.minorDropdown2.setItemText(8, _translate("Form", "AG - Plant Pathology and Crop Physiology"))
        self.minorDropdown2.setItemText(9, _translate("Form", "AG - Renewable Natural Resources"))
        self.minorDropdown2.setItemText(10, _translate("Form", "AG - Textiles, Apparel Design, and Merchandising"))
        self.minorDropdown2.setItemText(11, _translate("Form", "ART - Architecture"))
        self.minorDropdown2.setItemText(12, _translate("Form", "ART - Art"))
        self.minorDropdown2.setItemText(13, _translate("Form", "ART - Interior Design"))
        self.minorDropdown2.setItemText(14, _translate("Form", "ART - Landscape Architecture"))
        self.minorDropdown2.setItemText(15, _translate("Form", "BUS - Accounting"))
        self.minorDropdown2.setItemText(16, _translate("Form", "BUS - Economics"))
        self.minorDropdown2.setItemText(17, _translate("Form", "BUS - FInance"))
        self.minorDropdown2.setItemText(18, _translate("Form", "BUS - ISDS"))
        self.minorDropdown2.setItemText(19, _translate("Form", "BUS - Management"))
        self.minorDropdown2.setItemText(20, _translate("Form", "BUS - Marketing"))
        self.minorDropdown2.setItemText(21, _translate("Form", "COAST - Environmental Sciences"))
        self.minorDropdown2.setItemText(22, _translate("Form", "COAST - Oceanography & Coastal Sciences"))
        self.minorDropdown2.setItemText(23, _translate("Form", "ENG - Biological Engineering"))
        self.minorDropdown2.setItemText(24, _translate("Form", "ENG - Chemical Engineering"))
        self.minorDropdown2.setItemText(25, _translate("Form", "ENG - Civil Engineering"))
        self.minorDropdown2.setItemText(26, _translate("Form", "ENG - Construction Management"))
        self.minorDropdown2.setItemText(27, _translate("Form", "ENG - Computer Engineering"))
        self.minorDropdown2.setItemText(28, _translate("Form", "ENG - Electrical Engineering"))
        self.minorDropdown2.setItemText(29, _translate("Form", "ENG - Environmental Engineering"))
        self.minorDropdown2.setItemText(30, _translate("Form", "ENG - Industrial Engineering"))
        self.minorDropdown2.setItemText(31, _translate("Form", "ENG - Mechanical Engineering"))
        self.minorDropdown2.setItemText(32, _translate("Form", "ENG - Petroleum Engineering"))
        self.minorDropdown2.setItemText(33, _translate("Form", "HSE - Education"))
        self.minorDropdown2.setItemText(34, _translate("Form", "HSE - Human Resource Education & Workforce Development"))
        self.minorDropdown2.setItemText(35, _translate("Form", "HSE - Kinesiology"))
        self.minorDropdown2.setItemText(36, _translate("Form", "HSE - Library & Information Sciences"))
        self.minorDropdown2.setItemText(37, _translate("Form", "HSE - Social Work"))
        self.minorDropdown2.setItemText(38, _translate("Form", "HSS - Aerospace Studies"))
        self.minorDropdown2.setItemText(39, _translate("Form", "HSS - Communication Sciences & Disorders"))
        self.minorDropdown2.setItemText(40, _translate("Form", "HSS - Communication Studies"))
        self.minorDropdown2.setItemText(41, _translate("Form", "HSS - English"))
        self.minorDropdown2.setItemText(42, _translate("Form", "HSS - Foreign Languages & Literatures"))
        self.minorDropdown2.setItemText(43, _translate("Form", "HSS - French Studies"))
        self.minorDropdown2.setItemText(44, _translate("Form", "HSS - Geography & Anthropology"))
        self.minorDropdown2.setItemText(45, _translate("Form", "HSS - History"))
        self.minorDropdown2.setItemText(46, _translate("Form", "HSS - Military Science"))
        self.minorDropdown2.setItemText(47, _translate("Form", "HSS - Philosophy & Religious Studies"))
        self.minorDropdown2.setItemText(48, _translate("Form", "HSS - Psychology"))
        self.minorDropdown2.setItemText(49, _translate("Form", "HSS - Sociology"))
        self.minorDropdown2.setItemText(50, _translate("Form", "MCOMM - Journalism"))
        self.minorDropdown2.setItemText(51, _translate("Form", "MCOMM - Digital Advertising"))
        self.minorDropdown2.setItemText(52, _translate("Form", "MCOMM - Political Communication"))
        self.minorDropdown2.setItemText(53, _translate("Form", "MCOMM - Public Relations"))
        self.minorDropdown2.setItemText(54, _translate("Form", "MDA - Music"))
        self.minorDropdown2.setItemText(55, _translate("Form", "MDA - Theatre"))
        self.minorDropdown2.setItemText(56, _translate("Form", "SCI - Biological Sciences"))
        self.minorDropdown2.setItemText(57, _translate("Form", "SCI - Chemistry"))
        self.minorDropdown2.setItemText(58, _translate("Form", "SCI - Geology & Geophysics"))
        self.minorDropdown2.setItemText(59, _translate("Form", "SCI - Mathematics"))
        self.minorDropdown2.setItemText(60, _translate("Form", "SCI - Physics & Astronomy"))
        self.minorDropdown2.setItemText(61, _translate("Form", "SCI - Natural Science"))
        self.minorDropdown2.setItemText(62, _translate("Form", "Undecided - Arts & Humanities"))
        self.minorDropdown2.setItemText(63, _translate("Form", "Undecided - Science & Engineering"))
        self.minorDropdown2.setItemText(64, _translate("Form", "Undecided - Social Science"))
        self.minorDropdown2.setItemText(65, _translate("Form", "Other"))
        self.label_2.setText(_translate("Form", "Second Major:"))
        self.label.setText(_translate("Form", "Second Minor:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

